# Generated by Django 4.0.2 on 2022-03-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_image_path_remove_video_path_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newimage',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='newimage',
            name='id_new',
        ),
        migrations.RemoveField(
            model_name='newvideo',
            name='id_new',
        ),
        migrations.RemoveField(
            model_name='newvideo',
            name='id_video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Загрузить/Удалить изображение'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
        migrations.DeleteModel(
            name='NewImage',
        ),
        migrations.DeleteModel(
            name='NewVideo',
        ),
    ]
