# Generated by Django 4.0.2 on 2022-04-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employee_options_postvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postvideo',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='postvideo',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
