# Generated by Django 4.0.2 on 2022-04-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_postimage_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='slider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Images', to='main.slider'),
        ),
    ]
