# Generated by Django 4.0.2 on 2022-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vacancies_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
    ]
