# Generated by Django 4.0.2 on 2022-04-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_vacancies_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'ordering': ['-id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст (ссылается на новости)'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
